idp/urls.py
from django.urls import path

from djangosaml2idp import views as dsidp_views
from . import views

app_name = 'djangosaml2idp'

urlpatterns = [
    path('sso/init/', dsidp_views.SSOInitView.as_view(),
         name="saml_idp_init"),
    path('sso/<str:binding>/', dsidp_views.sso_entry, name="saml_login_binding"),
    path('login/process/', dsidp_views.LoginProcessView.as_view(), name='saml_login_process'),
    path('login/process_multi_factor/', dsidp_views.get_multifactor, name='saml_multi_factor'),
    path('slo/<str:binding>/', views.LogoutProcessView.as_view(), name="saml_logout_binding"),
    path('metadata/', dsidp_views.metadata, name='saml2_idp_metadata'),
]

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import HomeView, OpenIDApplicationCreateView, OpenIDApplicationDeleteView, \
    OpenIDApplicationEditView, \
    SamlMetadataView, \
    SamlSPCreateView, \
    SamlSPDeleteView, SamlSPEditView, UserCreateView, UserEditView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('saml-metadata/<int:sp>/', SamlMetadataView.as_view(),
         name='saml-metadata'),
    path('saml-sp/new/', SamlSPCreateView.as_view(),
         name='sp-create'),
    path('saml-sp/<int:pk>/delete/', SamlSPDeleteView.as_view(),
         name='sp-delete'),
    path('saml-sp/<int:pk>/', SamlSPEditView.as_view(),
         name='sp-edit'),
    path('oidc-app/new/', OpenIDApplicationCreateView.as_view(),
         name='oidc-app-create'),
    path('oidc-app/<int:pk>/delete/', OpenIDApplicationDeleteView.as_view(),
         name='oidc-app-delete'),
    path('oidc-app/<int:pk>/', OpenIDApplicationEditView.as_view(),
         name='oidc-app-edit'),
    path('user/new/', UserCreateView.as_view(),
         name='user-create'),
    path('user/<int:pk>/', UserEditView.as_view(),
         name='user-edit'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

testidp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from idp.views import ConnectDiscoveryInfoView

handler404 = 'main.error_views.error_404'
handler500 = 'main.error_views.error_500'
handler403 = 'main.error_views.error_403'
handler400 = 'main.error_views.error_400'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('saml/idp/', include('idp.urls')),
    re_path(
        r"^o/\.well-known/openid-configuration/?$",
        ConnectDiscoveryInfoView.as_view(),
        name="oidc-connect-discovery-info",
    ),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path('impersonate/', include('impersonate.urls')),
    path('cdhcore/', include('cdh.core.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)


admin.site.site_header = ''
admin.site.site_title = ''
admin.site.index_title = ''


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

main/forms.py
from django import forms
from django.conf import settings

from cdh.core.forms import TemplatedForm, TemplatedModelForm, \
    BootstrapCheckboxInput, BootstrapSelect
from djangosaml2idp.models import ServiceProvider
from oauth2_provider.models import Application

from main.models import User


class UserForm(TemplatedModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'uid',
            'password',
            'givenName',
            'sn',
            'cn',
            'displayName',
            'schacHomeOrganization',
            'eduPersonPrincipalName',
            'schacPersonalUniqueCode',
            '_eduPersonEntitlement',
            '_eduPersonAffiliation',
            '_isMemberOf',
            'is_active',
            'is_staff',
            'is_superuser',
        ]
        widgets = {
            'is_staff': BootstrapCheckboxInput,
            'is_superuser': BootstrapCheckboxInput,
            'is_active': BootstrapCheckboxInput,
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        if 'password' in self.initial and self.initial['password'].startswith(
                'plain'):
            self.initial['password'] = self.initial['password'].split('$', 2)[1]

    def clean_password(self):
        return f"plain${self.cleaned_data['password']}"


class ApplicationForm(TemplatedModelForm):
    class Meta:
        model = Application
        fields = [
            'name',
            'redirect_uris',
            'skip_authorization',
        ]
        widgets = {
            'redirect_uris': forms.Textarea,
            'post_logout_redirect_uris': forms.Textarea,
            'skip_authorization': BootstrapCheckboxInput,
        }

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)

        if 'client_secret' in self.initial and self.initial['client_secret'].startswith(
                'plain'):
            self.initial['client_secret'] = self.initial['client_secret'].split('$', 2)[1]

    def clean_client_secret(self):
        return f"plain${self.cleaned_data['client_secret']}"


class SPCreateForm(TemplatedForm):

    name = forms.CharField(
        help_text="Human friendly name, not required",
        required=False
    )

    description = forms.CharField(
        widget=forms.Textarea,
        help_text="Detailed description, not required",
        required=False
    )

    entity_id = forms.CharField(
        required=True,
        help_text="Almost always the URL of the SP's metadata. (e.g. "
                  "'http://localhost:8000/saml/metadata/')"
    )

    metadata_url = forms.URLField(
        required=False,
        help_text="The IdP will import the metadata by fetching it from this "
                  "url, which is the recommended way to create a new SP"
    )

    metadata = forms.CharField(
        widget=forms.Textarea,
        required=False,
        help_text="If the above option doesn't work, copy+paste the metadata "
                  "manually here."
    )

    attribute_map = forms.CharField(
        widget=BootstrapSelect(
            choices=(
                ('UU', 'UU'),
                ('SC', 'SurfConext (sensible)'),
                ('SC_all', 'SurfConext (full)'),
                (None, 'Empty'),
            )
        ),
        help_text="This will load in a preset attribute map for ease of use. "
                  "Depending on your SP, you might need to create your own. ("
                  "It's recommended to load in the full SC attribute map in "
                  "that case, which contains all available attributes)",
        required=False,
        initial='UU',
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.HOSTED:
            self.fields['description'].help_text = ("Please fill in contact "
                                                    "details for your app here")
            self.fields['description'].required = True
            self.fields['name'].help_text = "The name of your app"
            self.fields['name'].required = True

    def clean(self):
        cleaned_data = super().clean()

        if (not cleaned_data['metadata'] and not cleaned_data[
           'metadata_url']) or \
            (cleaned_data['metadata'] and cleaned_data['metadata_url']):
            self.add_error('metadata', 'Exactly one of these two fields need '
                                       'to be filled')
            self.add_error('metadata_url', 'Exactly one of these two fields '
                                           'need to be filled')

        return cleaned_data


YES_NO_UNKNOWN = (
    (True, "Yes"),
    (False, "No"),
    (None, "IDP Default"),
)


class SPForm(TemplatedModelForm):

    class Meta:
        model = ServiceProvider
        fields = [
            'pretty_name',
            'entity_id',
            'description',
            'active',
            'remote_metadata_url',
            'local_metadata',
            'metadata_expiration_dt',
            '_attribute_mapping',
        ]
        widgets = {
            'active': BootstrapCheckboxInput,
            '_sign_response': BootstrapSelect(
                choices=YES_NO_UNKNOWN
            ),
            '_sign_assertion': BootstrapSelect(
                choices=YES_NO_UNKNOWN
            ),
            '_signing_algorithm': BootstrapSelect(
                choices=YES_NO_UNKNOWN
            ),
            '_digest_algorithm': BootstrapSelect,
            '_encrypt_saml_responses': BootstrapSelect(
                choices=YES_NO_UNKNOWN
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['_attribute_mapping'].help_text = """
        A dictionary mapping user attributes from the names used in the IdP to
        the desired name in the SAML response. The key should be the name in the
        IdP, the value the name in the SAML Response
        """
        self.fields['remote_metadata_url'].help_text = ""

        if settings.HOSTED:
            self.fields['description'].help_text = ("Please fill in contact "
                                                    "details for your app here")
            self.fields['description'].required = True
            self.fields['pretty_name'].help_text = "The name of your app"
            self.fields['pretty_name'].required = True

main/views.py
import json

import requests
from braces import views as braces
from django import forms
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from djangosaml2idp.models import ServiceProvider
from oauth2_provider.models import Application

from main.attribute_map_presets import SC, SC_ALL, UU
from main.forms import ApplicationForm, SPCreateForm, SPForm, UserForm
from main.models import User, UserMail, UserOU


class HomeView(braces.LoginRequiredMixin, generic.TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['service_providers'] = ServiceProvider.objects.all()
        context['openid_applications'] = Application.objects.all()
        context['users'] = User.objects.all()

        return context


class UserCreateView(braces.LoginRequiredMixin, generic.CreateView):
    model = User
    template_name = 'main/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('main:home')


class UserEditView(braces.LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = 'main/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('main:home')

    mail_formset = forms.inlineformset_factory(
        User,
        UserMail,
        fields=('email',),
        can_delete=True,
        extra=4
    )

    ou_formset = forms.inlineformset_factory(
        User,
        UserOU,
        fields=('name',),
        can_delete=True,
        extra=4
    )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mail_formset'] = kwargs.get(
            'mail_formset',
            self.mail_formset(instance=self.get_object())
        )
        context['ou_formset'] = kwargs.get(
            'ou_formset',
            self.ou_formset(instance=self.get_object())
        )

        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=self.object)
        mail_formset = self.mail_formset(request.POST, instance=self.object)
        ou_formset = self.ou_formset(request.POST, instance=self.object)

        if form.is_valid() and mail_formset.is_valid() and ou_formset.is_valid():
            return self.form_valid(form, mail_formset, ou_formset)
        elif not form.is_valid():
            return self.form_invalid(form)

        return self.render_to_response(
            self.get_context_data(
                form=form,
                mail_formset=mail_formset
            )
        )

    def form_valid(self, form, mail_formset, ou_formset):
        mail_formset.save()
        ou_formset.save()
        return super().form_valid(form)



class SamlSPEditView(braces.LoginRequiredMixin, generic.UpdateView):
    model = ServiceProvider
    template_name = 'main/sp_form.html'
    form_class = SPForm
    success_url = reverse_lazy('main:home')


class SamlSPCreateView(braces.LoginRequiredMixin, generic.FormView):
    template_name = 'main/sp_form_create.html'
    form_class = SPCreateForm
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        resp = super().form_valid(form)

        sp = ServiceProvider()
        sp.pretty_name = form.cleaned_data['name']
        sp.description = form.cleaned_data['description']
        sp._sign_response = True
        sp._sign_assertion = True
        sp._processor = settings.SAML_IDP_CONFIG['processor']
        sp.entity_id = form.cleaned_data['entity_id']

        if form.cleaned_data['metadata_url']:
            data = requests.get(form.cleaned_data['metadata_url'])
            sp.local_metadata = str(data.text)
            sp.remote_metadata_url = form.cleaned_data['metadata_url']
        else:
            sp.local_metadata = form.cleaned_data['metadata']

        am = form.cleaned_data['attribute_map']
        if am == "UU":
            sp._attribute_mapping = json.dumps(UU, indent=2)
        elif am == "SC":
            sp._attribute_mapping = json.dumps(SC, indent=2)
        elif am == "SC_all":
            sp._attribute_mapping = json.dumps(SC_ALL, indent=2)

        sp.save()

        return resp


class SamlSPDeleteView(braces.LoginRequiredMixin, generic.DeleteView):
    model = ServiceProvider
    success_url = reverse_lazy('main:home')
    template_name = 'main/sp_form_delete.html'


class SamlMetadataView(braces.LoginRequiredMixin, generic.View):

    def dispatch(self, request, sp, *args, **kwargs):
        serviceProvider = ServiceProvider.objects.get(
            pk=sp
        )

        if serviceProvider.remote_metadata_url:
            return HttpResponseRedirect(
                serviceProvider.remote_metadata_url
            )

        if serviceProvider.local_metadata:
            return HttpResponse(
                content=serviceProvider.local_metadata,
                content_type="application/xml"
            )

        raise Http404


class OpenIDApplicationEditView(braces.LoginRequiredMixin, generic.UpdateView):
    model = Application
    template_name = 'main/oidc_form.html'
    form_class = ApplicationForm
    success_url = reverse_lazy('main:home')


class OpenIDApplicationCreateView(braces.LoginRequiredMixin, generic.FormView):
    template_name = 'main/oidc_form_create.html'
    form_class = ApplicationForm
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        resp = super().form_valid(form)

        app = Application()
        app.name = form.cleaned_data['name']
        app.redirect_uris = form.cleaned_data['redirect_uris']
        app.skip_authorization = form.cleaned_data['skip_authorization']

        # Hardcoded values
        app.user = self.request.user
        app.client_type = "public"
        app.authorization_grant_type = "authorization-code"
        app.hash_client_secret = False
        app.algorithm = "RS256"

        app.save()

        return resp

class OpenIDApplicationDeleteView(braces.LoginRequiredMixin, generic.DeleteView):
    model = Application
    success_url = reverse_lazy('main:home')
    template_name = 'main/oidc_form_delete.html'

main/templates/main/index.html
{% extends "base/app_base.html" %}

{% block content %}
    {% if hosted %}
        <div class="uu-hero text-bg-teal">
            <h1>Welcome</h1>
        </div>
        <div class="uu-container">
            <p>
                Welcome to our Development IdP, the IdP you can use if you want
                to connect a development or testing version of an app to an IdP
                you want to have more control over.
                <br/>
                Anyone can use at Humanities IT can use this IdP if they want,
                but please try to keep things tidy.
            </p>
            <div class="alert alert-warning w-100">
                This is a reminder that passwords are stored in plaintext! Do
                not connect <em>anything</em> that contains sensitive
                information to this IdP. (And obviously, do not create users
                with passwords you actually use).
            </div>
        </div>
    {% endif %}
    <div class="uu-hero text-bg-teal justify-content-between align-items-center">
        <h1>SAML Service Providers</h1>
        <a class="btn btn-secondary" href="{% url 'main:sp-create' %}">
            New
        </a>
    </div>
    <div class="uu-container">
        {% if not hosted %}
            <div class="col-12">
                <p>
                    If you have multiple SP's you work on, remember that IdPs
                    load config based on the EntityID. Thus, it is very
                    important that apps with diverging config/different certs
                    have a unique EntityID. This can be done by either hosting
                    the metadata at a (slightly) different URL, or running your
                    app on different ports. (8000, 8001, etc).
                </p>
                <p>
                    Apps using the exact same config (and certificates) can
                    share an entry here.
                </p>
            </div>
        {% endif %}
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Entity ID</th>
                        <th>Description</th>
                        <th>Metadata URL</th>
                        <th>Active</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for sp in service_providers %}
                        <tr>
                            <td>
                                {{ sp.pretty_name }}
                            </td>
                            <td>
                                {{ sp.entity_id }}
                            </td>
                            <td>
                                {{ sp.description }}
                            </td>
                            <td>
                                <a href="{% url 'main:saml-metadata' sp.pk %}" target="_blank">
                                    Metadata
                                </a>
                            </td>
                            <td>
                                {{ sp.active|yesno }}
                            </td>
                            <td>
                                <a href="{% url 'main:sp-edit' sp.pk %}">Edit</a>
                                <a href="{% url 'main:sp-delete' sp.pk %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="uu-hero text-bg-teal justify-content-between align-items-center">
        <h1>OpenID Connect Applications</h1>
        <a class="btn btn-secondary" href="{% url 'main:oidc-app-create' %}">
            New
        </a>
    </div>
    <div class="uu-container">
        <div class="col-12">
            <p>
                OIDC discovery info can be found <a href="{% url 'oauth2_provider:oidc-connect-discovery-info' %}" target="_blank">here</a>.
            </p>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Client ID</th>
                        <th>Client Secret</th>
                        <th>Redirect uris</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for app in openid_applications %}
                        <tr>
                            <td>
                                {{ app.name }}
                            </td>
                            <td class="text-break">
                                {{ app.client_id }}
                            </td>
                            <td class="text-break">
                                {{ app.client_secret }}
                            </td>
                            <td>
                                {{ app.redirect_uris }}
                            </td>
                            <td>
                                <a href="{% url 'main:oidc-app-edit' app.pk %}">Edit</a>
                                <a href="{% url 'main:oidc-app-delete' app.pk %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="uu-hero text-bg-teal justify-content-between align-items-center">
        <h1>Users</h1>

        <a class="btn btn-secondary" href="{% url 'main:user-create' %}">
            New
        </a>
    </div>
    <div class="uu-container">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Display Name</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Home organisation</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr>
                            <td>
                                {{ user.username }}
                            </td>
                            <td>
                                {{ user.get_password }}
                            </td>
                            <td>
                                {{ user.displayName }}
                            </td>
                            <td>
                                {{ user.givenName }}
                            </td>
                            <td>
                                {{ user.sn }}
                            </td>
                            <td>
                                {{ user.schacHomeOrganization }}
                            </td>
                            <td>
                                <a href="{% url 'main:user-edit' user.pk %}">Edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

main/templates/main/oidc_form.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Edit OIDC application</h1>
    </div>
    <div class="uu-container">
        <div class="col-12">
            <p>
                This is a subset of the available settings, with advanced options removed. Please edit the app in the
                <a href="{% url 'admin:oauth2_provider_application_change' object.pk %}">Django Admin</a> for all options.
            </p>
        </div>
        <form method="post" enctype="multipart/form-data" class="uu-form uu-form-no-gap mt-3">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-2">
                Save
            </button>
        </form>
    </div>
{% endblock %}

main/templates/main/oidc_form_create.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Create OIDC application</h1>
    </div>
    <div class="uu-container">
        <form method="post" enctype="multipart/form-data" class="uu-form w-100 uu-form-no-gap">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-3">
                Save
            </button>
        </form>
    </div>
{% endblock %}

main/templates/main/oidc_form_delete.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Delete OIDC App</h1>
    </div>
    <div class="uu-container">
        <p>
            Are you sure you want to delete application '{{ object }}'?
        </p>
        <form method="post" enctype="multipart/form-data" class="uu-form w-100 uu-form-no-gap">
            {% csrf_token %}
            <div class="btn-group">
                <button type="submit" class="btn btn-primary">
                    Delete
                </button>
                <a href="{% url 'main:home' %}" class="btn btn-secondary">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/sp_form.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Edit SP</h1>
    </div>
    <div class="uu-container">
        <div class="col-12">
            <p>
                This is a subset of the available settings, with advanced options removed. Please edit the SP in the
                <a href="{% url 'admin:djangosaml2idp_serviceprovider_change' object.pk %}">Django Admin</a> for all options.
            </p>
        </div>
        <form method="post" enctype="multipart/form-data" class="uu-form uu-form-no-gap mt-3">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-2">
                Save
            </button>
        </form>
    </div>
{% endblock %}

main/templates/main/sp_form_create.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Create SP</h1>
    </div>
    <div class="uu-container">
        <form method="post" enctype="multipart/form-data" class="uu-form w-100 uu-form-no-gap">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-3">
                Save
            </button>
        </form>
    </div>
{% endblock %}

main/templates/main/sp_form_delete.html
{% extends 'base/app_base.html' %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        <h1>Delete SP</h1>
    </div>
    <div class="uu-container">
        <p>
            Are you sure you want to delete SP '{{ object }}'?
        </p>
        <form method="post" enctype="multipart/form-data" class="uu-form w-100 uu-form-no-gap">
            {% csrf_token %}
            <div class="btn-group">
                <button type="submit" class="btn btn-primary">
                    Delete
                </button>
                <a href="{% url 'main:home' %}" class="btn btn-secondary">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/user_form.html
{% extends 'base/app_base.html' %}

{% block html_head %}
    {{ block.super }}
    <script nonce="{{ request.csp_nonce }}">
        function hideExtraForms(numExisting, form_class) {
            $(form_class).each((idx, el) => {
                if (idx >= numExisting) {
                    $(el).hide();
                }
            });
        }
        function setupAddBtn(button_id, form_class) {
            $(button_id).click((event) => {
                event.preventDefault();
                let hidden = $(form_class+':hidden');
                hidden.last().show();

                if (hidden.length - 1 <= 0) {
                    $(button_id).hide();
                }
            });
        }

        $(function() {
            setupAddBtn("#add_se", '.se-form');
            setupAddBtn("#add_ou", '.ou-form');
            hideExtraForms({{ object.usermail_set.count }}, '.se-form');
            hideExtraForms({{ object.userou_set.count }}, '.ou-form');
        });
    </script>
{% endblock %}

{% block content %}
    <div class="uu-hero text-bg-teal">
        {% if object %}
            <h1>Edit user</h1>
        {% else %}
            <h1>Create user</h1>
        {% endif %}
    </div>
    <div class="uu-container">
        <div class="col-12">
            <p>
                These attributes are named after the attributes used in
                SurfConext. See
                <a href="https://wiki.surfnet.nl/display/surfconextdev/Attributes+and+SAML">
                their documentation
                </a> for detailed descriptions of all attributes.
            </p>
            <p>
                We don't know how all of these attributes map to the UU IdP, but
                if we do, it will be in the help text. If you know any more
                attribute names used by the UU IdP, please do tell.
            </p>
        </div>
        <form method="post" enctype="multipart/form-data" class="uu-form mt-3">
            {% csrf_token %}
            {{ form }}

            {% if object %}
                <div class="uu-form-row">
                    <div class="uu-form-field">
                        <label class="form-label">
                            Emails
                        </label>
                        <div>
                            {{ mail_formset.management_form }}
                            {% for se_form in mail_formset %}
                                <div class="se-form">
                                    {{ se_form.as_p }}
                                    <hr/>
                                </div>
                            {% endfor %}
                            <a href="#" id="add_se">+ Add new</a>
                        </div>
                    </div>
                </div>
                <div class="uu-form-row">
                    <div class="uu-form-field">
                        <label class="form-label">
                            Organizational Unit Name
                        </label>
                        <div>
                            {{ ou_formset.management_form }}
                            {% for ou_form in ou_formset %}
                                <div class="ou-form">
                                    {{ ou_form.as_p }}
                                    <hr/>
                                </div>
                            {% endfor %}
                            <a href="#" id="add_ou">+ Add new</a>
                        </div>
                    </div>
                    <div class="uu-form-help">
                        Maps to 'uuLegacyDepartment' in the UU IdP
                    </div>
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary mt-3">
                Save
            </button>
        </form>
    </div>
{% endblock %}